# Site settings
title: Andy Hughes || Resumé
description: Andy's Portfolio
favicon: /assets/img/Me.JPG
baseurl: https://andyhughes5423.github.io/resumecard
url: https://andyhughes5423.github.io/resumecard
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Andy Hughes
  title: Business Technology Analyst
  address: Chicago, IL
  email: andyhughes5423@yahoo.com
  link: http://ddbullfrog.com
  weibo:
  github: andyhughes5423
  linkedin: andyhughes5423
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: BMO Financial Group
      location: Chicago, IL
      title: Technology Analyst
      started: 2019
      duration: (May 2019 - Present)
      description: Worked with project stakeholders to validate their requirements and analysis models via techniques such as reviews and walkthroughs. Recommended approaches to streamline and integrate technological processes in the organization to improve overall efficiency.
    - work2:
      company: Expeditors International
      location: Bensenville, IL
      title: Data Analytics Intern
      started: 2018
      duration: (May 2018 - Aug 2018)
      description: Automated internal reporting by developing Macro templates with VBA programming. Visualized data by utilizing Microsoft Power BI in order to customize data techniques in internal reporting.
  educationHistory:
    - education1:
      organization: University of Iowa, Tippie College of Business
      location: Iowa City, IA
      degree: BBA
      major: Business Analytics and Information Systems
      started: 2015
      duration: (Aug 2015 - May 2019)
      description: HawkTrade - Member
  languages:
    - language1:
      name: English
      proficiency: Native
    - language2:
      name: Spanish
      proficiency: Intermediate
  programmingSkills:
    - skill1:
      name: SQL
      percentage: 90%
    - skill2:
      name: R
      percentage: 90%
    - skill3:
      name: PL/SQL
      percentage: 80%
    - skill4:
      name: VBA
      percentage: 80%
    - skill5:
      name: C++
      percentage: 70%
